import {t,lang,setLanguage} from './i18n/i18n.js';
import {state,persist,setTheme} from './state.js';
import {analyzeWaste,generateGuide} from './integrations/ai.js';
import {getCurrentLocation} from './integrations/location.js';
import {users} from './mock/users.js';
import {getOrCreateRecityIdentity, restoreRecityIdentity, updateIdentityPreferences} from './integrations/supabase.js';
import {preparePhoto} from './photo.js';
import {submitComplaint} from './integrations/complaints.js';

const app=document.querySelector('#app');
const el=(strings,...values)=>strings.reduce((out,s,i)=>out+s+(values[i]??''),'');
const statusText=s=>({pending:t('pending'),review:t('review'),assigned:t('assigned'),collected:t('collected')})[s]||s;
const hazardBadge=h=>`<span class="badge ${h==='high'?'danger':h==='medium'?'warning':'success'}">${t(h)}</span>`;
const iconFor=i=>i?.emoji||'♻️';
const localWaste=r=>r.item==='bottle'?t('plasticBottle'):r.item==='cardboard'?t('cardboardBox'):r.item==='glass'?t('brokenGlass'):r.item==='battery'?t('battery'):r.waste;
function scientificProfile(item){
 const material=(item.material||'').toLowerCase(),condition=(item.condition||'').toLowerCase(),unsafe=item.hazard==='high'||/battery|electronic|chemical|medical|unknown/.test(material);
 const damaged=/damage|crack|chip|sharp|broken|poor/.test(condition);
 let kind='unknown',scores={material:45,condition:damaged?25:55,durability:45,safety:damaged?20:50,environment:55};
 if(/pet|plastic/.test(material)){kind='pet';scores={material:90,condition:damaged?35:85,durability:80,safety:damaged?25:80,environment:85}}
 else if(/glass/.test(material)){kind='glass';scores={material:75,condition:damaged?10:85,durability:85,safety:damaged?5:55,environment:80}}
 else if(/cardboard|paper/.test(material)){kind='cardboard';scores={material:65,condition:damaged?25:75,durability:35,safety:damaged?30:85,environment:80}}
 else if(/aluminium|aluminum|metal|steel|tin/.test(material)){kind='metal';scores={material:70,condition:damaged?30:75,durability:85,safety:damaged?20:55,environment:90}}
 if(unsafe){kind='unsafe';scores={material:0,condition:0,durability:0,safety:0,environment:70}}
 const score=Math.round(scores.material*.30+scores.condition*.20+scores.durability*.20+scores.safety*.20+scores.environment*.10);
 return {kind,scores,score,band:score>=75?'scoreHigh':score>=45?'scoreMedium':'scoreLow'};
}
function toast(message){document.querySelector('#toast-region').innerHTML=`<div class="toast">${message}</div>`;setTimeout(()=>document.querySelector('#toast-region').innerHTML='',3800)}
function shell(content,{municipal=false}={}){return el`<main class="app-shell ${municipal?'municipal-content':'citizen-content'}">
  <header class="topbar"><button class="brand" data-go="home" aria-label="${t('appName')} ${t('home')}"><span class="brand-mark">⌁</span>${t('appName')}</button>
  <div class="top-actions"><button class="icon-btn lang-btn" data-action="language" aria-label="${t('language')}">${lang()==='en'?'मराठी':'EN'}</button><button class="icon-btn" data-action="theme" aria-label="${t('dark')}">${state.theme==='dark'?'☀':'◐'}</button></div></header>${content}
  ${municipal?'':bottomNav()}</main>`}
function bottomNav(){return `<nav class="bottom-nav" aria-label="Primary"><div class="bottom-nav-inner">${[['home','⌂'],['reports','▤'],['impact','◌'],['profile','☺']].map(([x,i])=>`<button class="nav-item ${state.screen===x?'active':''}" data-go="${x}"><span>${i}</span>${t(x)}</button>`).join('')}</div></nav>`}
function head(title,back='home'){return `<div class="page-head"><button class="back-btn" data-go="${back}" aria-label="${t('back')}">‹</button><h1>${title}</h1></div>`}
function home(){const u=state.user;return shell(el`<section class="screen">
  <div class="hero"><span class="eyebrow">${t('tagline')}</span><h1>${t('giveLife')}</h1><p>${t('photoHint')}</p><button class="btn btn-primary" data-go="capture">⌁ ${t('takePhoto')}</button></div>
  <div class="home-grid"><div class="section"><div class="section-title"><h2>${t('yourEcoIdentity')}</h2><button class="text-link" data-go="profile">${t('profile')}</button></div>
  <div class="card identity"><span class="avatar">${u.emoji}</span><div><h3>${t(u.character)}</h3><p>${u.id} · ${t('level')} ${u.level}</p></div><div class="points"><strong>${u.points}</strong><br><small>${t('ecoPoints')}</small></div></div>
  <div class="section"><div class="metric-grid"><div class="metric"><strong>${u.reused}</strong><span>${t('itemsReused')}</span></div><div class="metric"><strong>${u.reports}</strong><span>${t('wasteReports')}</span></div><div class="metric"><strong>${u.diverted} kg</strong><span>${t('wasteDiverted')}</span></div></div></div></div>
  <div class="section"><div class="section-title"><h2>${t('quickActions')}</h2></div><div class="action-grid"><button class="quick-action" data-go="reports"><span>▤</span>${t('reports')}</button><button class="quick-action" data-go="impact"><span>◌</span>${t('impact')}</button><button class="quick-action" data-go="profile"><span>☺</span>${t('profile')}</button><button class="quick-action" data-go="municipal"><span>⌂</span>${t('help')}</button></div></div></div>
  <section class="section"><div class="section-title"><h2>${t('recentActivity')}</h2><button class="text-link" data-go="reports">${t('reports')}</button></div><div class="card"><div class="activity"><span class="activity-icon">✓</span><div><strong>${t('collected')}</strong><p>RC-10443 · ${t('mainRoad')}</p></div><small>+20</small></div><div class="activity"><span class="activity-icon">🌱</span><div><strong>${t('planter')}</strong><p>${t('itemsReused')}</p></div><small>+15</small></div></div></section></section>`)}
function welcome(){return shell(el`<section class="screen"><div class="hero"><span class="eyebrow">${t('tagline')}</span><h1>${t('welcome')}</h1><p>${t('welcomeBody')}</p></div><section class="section"><h2>${t('selectCharacter')}</h2><p>${t('characterBody')}</p><div class="choice-grid">${users.map((u,i)=>`<button class="choice ${state.user.character===u.character?'selected':''}" data-character="${i}"><span class="avatar">${u.emoji}</span><strong>${t(u.character)}</strong><span>${t(u.character+'Desc')}</span></button>`).join('')}</div><div class="button-stack"><button class="btn btn-primary btn-wide" data-action="start-identity">${t('startJourney')} →</button><small class="muted">${t('demoAccount')}</small></div></section></section>`)}
function capture(){return shell(el`<section class="screen">${head(t('takePhoto'))}<div class="photo-stage">${state.photo?`${photoPreview()}<h2>${t('analysis')}</h2><p>${state.photoName||t('photoHint')}</p>`:`<><span class="photo-emoji">📷</span><h2>${t('takePhoto')}</h2><p>${t('photoHint')}</p></>`}</div><div class="button-stack">${state.photo?`<button class="btn btn-primary btn-wide" data-action="analyze">⌁ ${t('analyzeWaste')}</button><button class="btn btn-ghost btn-wide" data-action="clear-photo">${t('retake')}</button>`:`<><label class="btn btn-primary btn-wide" for="camera-upload">◉ ${t('takePhoto')}</label><input class="sr-only" id="camera-upload" type="file" accept="image/*" capture="environment" /><label class="btn btn-secondary btn-wide" for="image-upload">▧ ${t('uploadGallery')}</label><input class="sr-only" id="image-upload" type="file" accept="image/*" /></>`}</div></section>`)}
function loading(){return shell(el`<section class="screen loading">${head(t('understanding'),'capture')}<div class="spinner" aria-label="Loading"></div><h2>${t('understanding')}</h2><div class="stages">${['looking','identifying','reuseCheck','safetyCheck','preparing'].map((x,i)=>`<div class="stage ${i<3?'active':''}">${t(x)}</div>`).join('')}</div></section>`)}
function photoPreview(){return state.photoSrc?`<div class="preview-photo has-image" role="img" aria-label="${t('image')}"><img src="${state.photoSrc}" alt="${t('image')}" /></div>`:`<div class="preview-photo" role="img" aria-label="${t('image')}"></div>`}
function analysis(){const a=state.analysis, item=state.selectedItem||a.items[0], hazard=item.hazard==='high', profile=scientificProfile(item);return shell(el`<section class="screen">${head(t('analysis'),'capture')}${photoPreview()}${hazard?`<div class="warning-box section"><strong>⚠ ${t('hazardous')}</strong><p>${t('hazardBody')}</p></div>`:''}<section class="section"><div class="analysis-banner"><strong>${t('detected')}: ${a.items.length}</strong><p>${a.summary}</p></div><div class="card section">${a.items.map((x,i)=>`<button class="waste-item" data-item="${i}" style="width:100%;border-left:0;border-right:0;border-top:0;background:transparent;color:var(--text);text-align:left"><span class="waste-thumb">${iconFor(x)}</span><div><h3>${t(x.key)}</h3><p>${t(x.material)} · ${t(x.reusable?'yes':'no')} ${t('reusable').toLowerCase()}</p></div>${hazardBadge(x.hazard)}</button>`).join('')}</div></section>
 <section class="section card"><h2>${t(item.key)}</h2><div class="detail-grid"><div class="detail"><span>${t('material')}</span><strong>${t(item.material)}</strong></div><div class="detail"><span>${t('condition')}</span><strong>${t(item.condition)}</strong></div><div class="detail"><span>${t('reusable')}</span><strong>${t(item.reusable?'yes':'no')}</strong></div><div class="detail"><span>${t('recyclable')}</span><strong>${t(item.recyclable?'yes':'no')}</strong></div><div class="detail"><span>${t('hazard')}</span><strong>${t(item.hazard)}</strong></div><div class="detail"><span>${t('confidence')}</span><strong>${item.confidence}%</strong></div></div>
  <div class="info-block"><h3>${t('whatIsThis')}</h3><p>${item.key==='plasticBottle'?t('bottleDesc'):item.suggestedAction||t('noReuse')}</p></div><div class="info-block"><h3>${t('scientificPassport')}</h3><p class="muted">${t('ruleBased')}</p><div class="detail-grid"><div class="detail"><span>${t('reusePotential')}</span><strong>${profile.score} / 100</strong></div><div class="detail"><span>${t('condition')}</span><strong>${t(profile.band)}</strong></div></div><h3>${t('characteristics')}</h3><p>${t(profile.kind+'Properties')}</p><h3>${t('bestNextLife')}</h3><p>${item.suggestedAction||t(profile.kind+'Use')}</p><h3>${t('plantSuitability')}</h3><p>${t(profile.kind+'Plant')}</p><h3>${t('avoidUse')}</h3><p>${t(profile.kind+'Avoid')}</p><details><summary>${t('scoreReason')}</summary><p>${t('scoreFormula')}</p><p>${t('material')}: ${profile.scores.material} · ${t('condition')}: ${profile.scores.condition} · ${t('safety')}: ${profile.scores.safety}</p></details></div><div class="info-block"><h3>${t('canReuse')}</h3><p>${item.reusable&&!hazard?item.safetyAdvice||t('bottleReuse'):t('noReuse')}</p></div>${item.reusable&&!hazard?`<div class="info-block"><h3>${t('reuseIdeas')}</h3>${(item.ideas||['storage']).map(x=>`<div class="idea">🌱 <strong>${t(x)}</strong><small>${t('easy')} · ${t('fifteen')}</small></div>`).join('')}</div>`:`<div class="info-block"><h3>${t('disposal')}</h3><p>${item.disposalAdvice||t('dryBin')}</p></div>`}<details class="info-block"><summary>${t('moreInfo')}</summary><p>${item.disposalAdvice||t('dryBin')}</p></details></section>
 <section class="section"><h2>${t('decisionTitle')}</h2><p>${t('decisionBody')}</p><div class="button-stack">${item.reusable&&!hazard?`<button class="btn btn-primary btn-wide" data-go="reuse">🌱 ${t('anotherLife')}</button>`:''}<button class="btn ${hazard?'btn-danger':'btn-secondary'} btn-wide" data-go="report">⚑ ${t('reportWaste')}</button></div></section></section>`)}
function reuse(){return shell(el`<section class="screen">${head(t('anotherLife'),'analysis')}<section><h2>${t('toolsTitle')}</h2><div class="chip-row">${['scissors','glue','tape','marker','screwdriver','paint','none'].map(x=>`<button class="chip ${state.tools.includes(x)?'selected':''}" data-tool="${x}">${x==='none'?t('no'):t(x)}</button>`).join('')}</div></section><section class="section"><h2>${t('timeTitle')}</h2><div class="chip-row">${[['5','fiveMinutes'],['15','fifteen'],['30','thirtyMinutes'],['60','oneHour'],['more','moreThanHour']].map(([v,label])=>`<button class="chip ${state.time===v?'selected':''}" data-time="${v}">${t(label)}</button>`).join('')}</div></section><div class="button-stack section"><button class="btn btn-primary btn-wide" data-action="guide">${t('continue')}</button><button class="btn btn-ghost btn-wide" data-go="report">${t('reportWaste')}</button></div></section>`)}
function guideScreen(){const g=state.guide;return shell(el`<section class="screen">${head(t('guide'),'reuse')}<div class="impact-hero"><span class="eyebrow">${t('plasticBottle')}</span><h2>🌱 ${t(g.title)}</h2><p>${t('easy')} · ${t('fifteen')}</p></div><section class="section card"><div class="detail-grid"><div class="detail"><span>${t('difficulty')}</span><strong>${t(g.difficulty)}</strong></div><div class="detail"><span>${t('time')}</span><strong>${t(g.time)}</strong></div></div><div class="info-block"><h3>${t('materials')}</h3><p>${g.materials.map(t).join(' · ')}</p></div><div class="info-block"><h3>${t('tools')}</h3><p>${g.tools.map(t).join(' · ')}</p></div><div class="info-block"><h3>${t('steps')}</h3>${g.steps.map((s,i)=>`<div class="step"><span class="step-num">${i+1}</span><div>${t(s)}</div></div>`).join('')}</div><div class="warning-box"><strong>⚠ ${t('safety')}</strong><p>${t(g.safety)}</p></div></section><button class="btn btn-primary btn-wide" data-action="complete-reuse">✓ ${t('backHome')}</button></section>`)}
function report(){const a=state.analysis;return shell(el`<section class="screen">${head(t('reportTitle'),'analysis')}<div class="warning-box" style="display:${a.items.some(x=>x.hazard==='high')?'block':'none'}"><strong>⚠ ${t('hazardous')}</strong><p>${t('hazardBody')}</p></div><section class="section card">${photoPreview()}<div class="form-field section"><label>${t('summary')}</label><input value="${a.summary}" aria-label="${t('summary')}" /></div><div class="form-field"><label>${t('address')}</label><input value="" placeholder="${t('address')}" aria-label="${t('address')}" /></div><div class="detail-grid"><div class="detail"><span>${t('coordinates')}</span><strong>—</strong></div><div class="detail"><span>${t('hazard')}</span><strong>${t(a.hazard)}</strong></div></div><div class="map section"><span class="marker" style="left:52%;top:43%">⌖</span></div><p class="muted">${t('locationUnavailable')}</p></section><button class="btn btn-primary btn-wide" data-action="submit-report">${t('submitReport')} →</button></section>`)}
function confirmation(){const r=state.selectedComplaint;return shell(el`<section class="screen">${head(t('reportSubmitted'),'home')}<div class="card success-hero"><div class="success-mark">✓</div><h2>${t('reportSubmitted')}</h2><p>${t('reportBody')}</p><div class="detail-grid"><div class="detail"><span>${t('reportId')}</span><strong>${r.id}</strong></div><div class="detail"><span>${t('status')}</span><strong>${statusText(r.status)}</strong></div><div class="detail"><span>${t('location')}</span><strong>${r.address}</strong></div><div class="detail"><span>${t('hazard')}</span><strong>${t(r.hazard)}</strong></div></div></div><div class="button-stack section"><button class="btn btn-primary btn-wide" data-go="reports">${t('reports')}</button><button class="btn btn-ghost btn-wide" data-go="home">${t('backHome')}</button></div></section>`)}
function reports(){const list=state.reports.filter(r=>r.citizen===state.user.id);return shell(el`<section class="screen">${head(t('reportHistory'))}${list.length?`<div class="card">${list.map(r=>reportCard(r)).join('')}</div>`:`<div class="card empty"><div>▤</div><h2>${t('noReports')}</h2><p>${t('noReportsBody')}</p><button class="btn btn-primary" data-go="capture">${t('takePhoto')}</button></div>`}</section>`)}
function reportCard(r){return `<button class="report-card" data-report="${r.id}" style="width:100%;border-left:0;border-right:0;border-top:0;background:transparent;color:var(--text);text-align:left"><span class="report-img">${r.photo}</span><div><h3>${r.id} · ${localWaste(r)}</h3><p>${r.address} · ${r.time==='Just now'?t('justNow'):r.time}</p></div><span class="badge ${r.status==='collected'?'success':r.hazard==='high'?'danger':'warning'}">${statusText(r.status)}</span></button>`}
function reportDetail(){const r=state.selectedComplaint;return shell(el`<section class="screen">${head(t('reportDetail'),'reports')}<div class="waste-photo" role="img" aria-label="${t('image')}">${r.photo}</div><section class="section card"><div class="section-title"><h2>${r.id}</h2>${hazardBadge(r.hazard)}</div><div class="detail-grid"><div class="detail"><span>${t('status')}</span><strong>${statusText(r.status)}</strong></div><div class="detail"><span>${t('citizenId')}</span><strong>${r.citizen}</strong></div><div class="detail"><span>${t('createdTime')}</span><strong>${r.time}</strong></div><div class="detail"><span>${t('coordinates')}</span><strong>${r.coords}</strong></div></div><div class="info-block"><h3>${t('aiSummary')}</h3><p>${r.summary}</p></div><div class="map"><span class="marker" style="left:${r.lat}%;top:${r.lon}%">⌖</span></div></section></section>`)}
function impact(){const u=state.user;const progress=Math.min(100,Math.round(u.points/1000*100));return shell(el`<section class="screen">${head(t('impactTitle'))}<div class="impact-hero"><span class="eyebrow">${t('ecoPoints')}</span><h2>${u.points}</h2><p>${t('impactBody')}</p><div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div><small>${t('level')} ${u.level} · ${progress}%</small></div><section class="section"><div class="metric-grid"><div class="metric"><strong>${u.reused}</strong><span>${t('itemsReused')}</span></div><div class="metric"><strong>${u.reports}</strong><span>${t('wasteReports')}</span></div><div class="metric"><strong>${u.collections}</strong><span>${t('collections')}</span></div></div></section><section class="section card"><h2>${t('progress')}</h2><p>Seedling → Eco Explorer → <strong>${t(u.character)}</strong> → Green Guardian</p></section></section>`)}
function profile(){const u=state.user;return shell(el`<section class="screen">${head(t('profile'))}<div class="card identity"><span class="avatar">${u.emoji}</span><div><h2>${t(u.character)}</h2><p>${u.id}</p></div></div><section class="section card"><h2>${t('settings')}</h2><div class="form-field"><label>${t('language')}</label><div class="segmented"><button class="${lang()==='en'?'active':''}" data-setlang="en">English</button><button class="${lang()==='mr'?'active':''}" data-setlang="mr">मराठी</button></div></div><div class="form-field"><label>${t('dark')}</label><div class="segmented"><button class="${state.theme==='light'?'active':''}" data-settheme="light">${t('light')}</button><button class="${state.theme==='dark'?'active':''}" data-settheme="dark">${t('dark')}</button></div></div></section><button class="btn btn-secondary btn-wide" data-go="municipal">${t('switchMunicipal')}</button></section>`)}
function municipal(){const reports=state.reports, active=reports.filter(r=>r.status!=='collected');return shell(el`<section class="screen">${head(t('municipal'),'home')}<div class="section-title"><div><span class="eyebrow">${t('municipalDemo')}</span><h1>${t('municipal')}</h1><p>${t('commandCenter')}</p></div><button class="btn btn-ghost" data-go="home">${t('switchCitizen')}</button></div><div class="alert"><span>🔔</span><div><strong>${t('newReports')}</strong><p>${t('plasticBottle')} · ${t('mainRoad')} · 2 min ago</p></div></div><section class="section dashboard-kpis"><div class="kpi"><strong>${active.length}</strong><span>${t('newReports')}</span></div><div class="kpi"><strong>${reports.filter(x=>x.status==='pending').length}</strong><span>${t('pendingReports')}</span></div><div class="kpi"><strong>${reports.filter(x=>x.hazard==='high').length}</strong><span>${t('highHazard')}</span></div><div class="kpi"><strong>${reports.filter(x=>x.status==='collected').length}</strong><span>${t('collectedToday')}</span></div></section><section class="section municipal-layout"><div class="map">${reports.map(r=>`<button class="marker" data-report="${r.id}" style="left:${r.lat}%;top:${r.lon}%" aria-label="${r.id}">⌖</button>`).join('')}</div><div class="card municipal-list"><h2>${t('complaintList')}</h2>${active.length?active.map(reportCard).join(''):`<div class="empty"><div>✓</div><p>${t('empty')}</p></div>`}</div></section></section>`,{municipal:true})}
function municipalDetail(){const r=state.selectedComplaint;return shell(el`<section class="screen">${head(t('reportDetail'),'municipal')}<div class="waste-photo" role="img" aria-label="${t('image')}">${r.photo}</div><section class="section card"><div class="section-title"><h2>${r.id}</h2>${hazardBadge(r.hazard)}</div><div class="detail-grid"><div class="detail"><span>${t('status')}</span><strong>${statusText(r.status)}</strong></div><div class="detail"><span>${t('citizenId')}</span><strong>${r.citizen}</strong></div><div class="detail"><span>${t('address')}</span><strong>${r.address}</strong></div><div class="detail"><span>${t('coordinates')}</span><strong>${r.coords}</strong></div></div><div class="info-block"><h3>${t('aiSummary')}</h3><p>${r.summary}</p></div><div class="map"><span class="marker" style="left:${r.lat}%;top:${r.lon}%">⌖</span></div></section><div class="button-stack section">${r.status!=='collected'?`<button class="btn btn-primary btn-wide" data-action="collect">✓ ${t('markCollected')}</button><button class="btn btn-ghost btn-wide" data-action="assign">${t('assign')}</button>`:`<div class="card success-hero"><div class="success-mark">✓</div><strong>${t('collected')}</strong><p>${t('municipalOperator')} · ${t('mockTimestamp')}</p></div>`}</div></section>`,{municipal:true})}
function render(){document.documentElement.dataset.theme=state.theme;let page={welcome,home,capture,loading,analysis,reuse,guide:guideScreen,report,confirmation,reports,reportDetail,impact,profile,municipal,municipalDetail}[state.screen]||home;app.innerHTML=page();}
function navigate(screen){state.screen=screen;render();window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-go],[data-action],[data-item],[data-tool],[data-time],[data-report],[data-character],[data-setlang],[data-settheme]');if(!target)return;
 if(target.dataset.go){navigate(target.dataset.go);return} if(target.dataset.character!==undefined){state.user=users[+target.dataset.character];render();return} if(target.dataset.item!==undefined){state.selectedItem=state.analysis.items[+target.dataset.item];render();return} if(target.dataset.tool){state.tools=state.tools.includes(target.dataset.tool)?state.tools.filter(x=>x!==target.dataset.tool):[...state.tools,target.dataset.tool];render();return} if(target.dataset.time){state.time=target.dataset.time;render();return} if(target.dataset.report){state.selectedComplaint=state.reports.find(x=>x.id===target.dataset.report);navigate(state.screen==='municipal'?'municipalDetail':'reportDetail');return} if(target.dataset.setlang){setLanguage(target.dataset.setlang);render();return} if(target.dataset.settheme){setTheme(target.dataset.settheme);render();return}
 const action=target.dataset.action;if(action==='language'){setLanguage(lang()==='en'?'mr':'en');render()} if(action==='theme'){setTheme(state.theme==='dark'?'light':'dark');render()} if(action==='start-identity'){target.disabled=true;target.textContent='…';try{state.user=await getOrCreateRecityIdentity({character:state.user.character,locale:lang()});navigate('home')}catch(error){toast(t('identityError'));render()}} if(action==='mock-photo'){state.photo=true;state.hazardous=false;render()} if(action==='clear-photo'){state.photo=false;render()} if(action==='hazard-demo'){state.photo=true;state.hazardous=true;render()} if(action==='analyze'){navigate('loading');state.analysis=await analyzeWaste({hazardous:state.hazardous});state.selectedItem=state.analysis.items[0];navigate('analysis')} if(action==='guide'){state.guide=await generateGuide();navigate('guide')} if(action==='complete-reuse'){state.user.reused++;state.user.points+=15;toast(`+15 ${t('ecoPoints')}`);navigate('home')} if(action==='submit-report'){target.disabled=true;target.textContent=t('submitting');await new Promise(r=>setTimeout(r,800));const loc=getMockLocation(),rid=`RC-${10500+state.reports.length}`;const r={id:rid,waste:state.analysis.summary,item:'bottle',photo:'🧴',address:loc.address,coords:`${loc.lat}, ${loc.lng}`,hazard:state.analysis.hazard,status:'pending',time:'Just now',citizen:state.user.id,summary:state.analysis.summary,lat:52,lon:43};state.reports.unshift(r);state.user.reports++;state.user.points+=10;state.selectedComplaint=r;persist();navigate('confirmation')} if(action==='collect'){const r=state.selectedComplaint;r.status='collected';r.collected_at=t('mockTimestamp');r.collected_by=t('municipalOperator');const u=users.find(x=>x.id===r.citizen);if(u)u.points+=20;persist();render();toast(t('collectionDone'))} if(action==='assign'){state.selectedComplaint.status='assigned';persist();render();toast(t('assign'))}
});
document.addEventListener('change',async e=>{if(!['image-upload','camera-upload'].includes(e.target.id)||!e.target.files?.length)return;try{const file=e.target.files[0];state.photoSrc=await preparePhoto(file);state.photoName=file.name;state.photo=true;state.hazardous=false;render()}catch(error){toast(error.message||t('photoError'));e.target.value=''}});
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='clear-photo'){e.preventDefault();e.stopImmediatePropagation();state.photo=false;state.photoSrc=null;state.photoName=null;state.analysis=null;state.selectedItem=null;render()}if(action==='analyze'){e.preventDefault();e.stopImmediatePropagation();if(!state.photoSrc){toast(t('photoError'));return}navigate('loading');try{state.analysis=await analyzeWaste({imageData:state.photoSrc,language:lang()});state.selectedItem=state.analysis.items[0];navigate('analysis')}catch(error){toast(t('analysisError'));navigate('capture')}}},true);
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action="submit-report"]');if(!target)return;e.preventDefault();e.stopImmediatePropagation();target.disabled=true;target.textContent=t('submitting');try{const inputs=document.querySelectorAll('.form-field input');const location=await getCurrentLocation();const saved=await submitComplaint({imageData:state.photoSrc,analysis:state.analysis,address:inputs[1]?.value,location});const r={id:saved.public_id,waste:state.analysis.summary,item:'bottle',photo:'🧴',address:inputs[1]?.value||t('locationUnavailable'),coords:location.lat?location.lat+', '+location.lng:'—',hazard:saved.hazard,status:'pending',time:'Just now',citizen:state.user.id,summary:state.analysis.summary,lat:52,lon:43};state.reports.unshift(r);state.user.reports++;state.user.points+=10;state.selectedComplaint=r;persist();navigate('confirmation')}catch(error){target.disabled=false;target.textContent=t('submitReport');toast(error.message||t('analysisError'))}},true);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTheme(state.theme);render();
restoreRecityIdentity().then(identity=>{if(identity){state.user=identity;navigate('home')}}).catch(()=>{});
