import { ensureIdentity, getMyProfile, requestCollector, reviewCollectorRequest, getOperationsData, getMyCollectorRequest, setAvailability, getCollectorData, respondToOffer, uploadProof, verifyProof } from './supabase.js';

const state = { view:'admin', tab:'home', adminUnlocked:false, request:null, reports:[], requests:[], offers:[], tasks:[], points:[], available:false, user:null };
const app=document.querySelector('#app'), toast=document.querySelector('#toast');
const notice=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)};
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const navigate=v=>{state.view=v;history.pushState({view:v},'',`#${v}`);render()};
const shell=(c,collector=false)=>`<div class="shell"><header class="top"><div class="brand"><span class="mark">↗</span>ReCity</div>${state.view==='admin'?'<button class="mode" data-action="join">Become a collector</button>':'<button class="mode" data-action="back">← Back</button>'}</header>${c}${collector?nav():''}</div>`;
const nav=()=>`<nav class="nav"><div class="nav-inner">${['home','alerts','tasks','points'].map(x=>`<button class="${state.tab===x?'active':''}" data-tab="${x}"><span>${({home:'⌂',alerts:'◉',tasks:'✓',points:'★'})[x]}</span>${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div></nav>`;
const report=r=>`<article class="report"><b>${esc(r.waste_summary||r.public_id)}</b><small>${esc(r.address||'Exact GPS location available')}</small><footer><span class="status ${r.status==='assigned'?'assigned':''}">${esc(r.status)}</span></footer></article>`;
const admin=()=>!state.adminUnlocked?`<section class="join"><p class="eyebrow">Protected workspace</p><h1>Municipal Dashboard</h1><p>Use your approved Municipal ReCity identity—no code is required.</p><button class="btn primary wide" data-action="check-admin">Continue as admin</button></section>`:`<p class="eyebrow">ReCity Operations</p><h1>Live municipal dashboard</h1><p>Reports, collector applications, and proof review in one place.</p><div class="map map-large"><span class="map-label">LIVE OPERATIONS MAP</span><span class="radius"></span><span class="pin report"></span></div><div class="section-head"><h2>Incoming reports</h2><span class="pill">${state.reports.length} live</span></div><section class="report-list">${state.reports.map(report).join('')||'<p>No reports yet.</p>'}</section><div class="section-head"><h2>Collector requests</h2><span class="pill">${state.requests.filter(r=>r.status==='pending').length} pending</span></div><section class="report-list">${state.requests.map(r=>`<article class="report"><b>${esc(r.display_name)}</b><small>Requested collector access</small><footer>${r.status==='pending'?`<button class="btn secondary small" data-action="reject-request" data-id="${r.id}">Reject</button><button class="btn primary small" data-action="approve-request" data-id="${r.id}">Approve</button>`:`<span class="status">${esc(r.status)}</span>`}</footer></article>`).join('')||'<p>No collector requests yet.</p>'}</section>`;
const join=()=>`<section class="join"><p class="eyebrow">Join ReCity</p><h1>Become a collector</h1><p>Send your name to the municipal team. No phone number or email is needed—this device gets its own ReCity identity.</p>${!state.request?'<form id="collector-form" class="card"><label>Your name</label><input name="name" required maxlength="80" placeholder="Enter your full name"><button class="btn primary wide">Send request</button></form>':state.request.status==='pending'?'<section class="card status-card"><div>⌛</div><h2>Request sent</h2><p>Keep this device. The municipal team can approve this exact ReCity identity.</p><button class="btn secondary wide" data-action="refresh-request">Check approval</button></section>':state.request.status==='approved'?'<section class="card status-card"><div>✓</div><h2>You’re approved</h2><p>Your collector dashboard is ready.</p><button class="btn primary wide" data-action="open-collector">Open collector dashboard</button></section>':'<section class="card status-card"><div>—</div><h2>Request not approved</h2><p>Please contact your municipal team for more information.</p></section>'}</section>`;
const offer=o=>`<section class="card alert-card"><div class="distance">${o.distance_meters?`${Math.round(o.distance_meters/100)/10} km away`:'Nearby'} · New report</div><h2>${esc(o.complaints?.waste_summary||'Waste report')}</h2><p>${esc(o.complaints?.address||'Exact report location is available for navigation.')}</p><div class="actions"><button class="btn secondary" data-action="reject-offer" data-id="${o.id}">Reject</button><button class="btn primary" data-action="accept-offer" data-id="${o.id}">Accept task</button></div></section>`;
const home=()=>`<p class="eyebrow">ReCity collector</p><h1>Ready to help?</h1><p>Your location is shared only while available.</p><section class="availability"><div><b>● ${state.available?'Available':'Unavailable'}</b><small>${state.available?'Nearby alerts are on':'Turn on availability to receive work'}</small></div><button class="switch ${state.available?'on':''}" data-action="availability"><i></i></button></section><div class="map"><span class="map-label">YOUR LIVE LOCATION</span><span class="radius"></span><span class="pin" style="left:32%;top:56%"></span>${state.offers.length?'<span class="pin report"></span>':''}</div>${state.offers[0]?offer(state.offers[0]):'<section class="card empty"><div>🌿</div><h2>No nearby reports</h2><p>Keep availability on to receive waste reports near you.</p></section>'}`;
const alerts=()=>`<p class="eyebrow">Nearby alerts</p><h1>Reports around you</h1><p>Accept only when you can collect it.</p>${state.offers.map(offer).join('')||'<section class="card empty"><div>✓</div><h2>You’re all caught up</h2><p>No nearby report needs a response.</p></section>'}`;
const tasks=()=>`<p class="eyebrow">My work</p><h1>Active tasks</h1><p>Upload a cleanup photo when work is complete.</p><section class="card">${state.tasks.map(t=>`<div class="task"><span class="task-icon">♻</span><div><b>${esc(t.complaints?.waste_summary||t.complaint_id)}</b><small>${esc(t.status.replaceAll('_',' '))}</small></div>${t.status==='proof_submitted'?'<span class="status">Awaiting review</span>':`<label class="assign">Proof<input class="proof-input" type="file" accept="image/*" data-task="${t.id}" hidden></label>`}</div>`).join('')||'<p>No active tasks.</p>'}</section>`;
const points=()=>{const n=state.points.reduce((v,p)=>v+p.points_delta,0);return `<p class="eyebrow">My progress</p><h1>Collector points</h1><section class="card points"><strong>${n}</strong><small>Verified cleanups earn +10. Explicit nearby rejections are −3.</small></section><section class="card">${state.points.map(p=>`<div class="task"><span class="task-icon">${p.points_delta>0?'＋':'−'}</span><div><b>${p.points_delta>0?'+':''}${p.points_delta} points</b><small>${esc(p.reason)}</small></div></div>`).join('')||'<p>Your point activity will appear here.</p>'}</section>`};
async function loadAdmin(){const d=await getOperationsData();state.reports=d.reports;state.requests=d.requests;state.tasks=(await getCollectorData()).tasks}
async function unlockAdmin(){await ensureIdentity();const profile=await getMyProfile();if(profile?.role!=='admin')throw new Error(`Municipal ID created: ${profile?.recity_id||'unknown'}. Send this ID to the municipal owner for one-time approval.`);state.adminUnlocked=true;await loadAdmin()}
async function loadCollector(){state.request=await getMyCollectorRequest();if(state.request?.status==='approved'){const d=await getCollectorData();state.offers=d.offers;state.tasks=d.tasks;state.points=d.points}}
function render(){let c,collector=false;if(state.view==='admin')c=admin();else if(state.view==='join')c=join();else{collector=true;c=({home,alerts,tasks,points})[state.tab]()}app.innerHTML=shell(c,collector)}
window.addEventListener('popstate',e=>{state.view=e.state?.view||'admin';render()});if(!history.state)history.replaceState({view:'admin'},'','#admin');
app.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='admin-form'){await ensureIdentity();await claimAdmin(new FormData(e.target).get('code'));state.adminUnlocked=true;await loadAdmin();notice('Municipal dashboard unlocked.');render()}if(e.target.id==='collector-form'){await ensureIdentity();await requestCollector(new FormData(e.target).get('name').trim());await loadCollector();notice('Collector request sent.');render()}}catch(x){notice(x.message||'Could not complete that action.')}});
app.addEventListener('change',async e=>{const i=e.target;if(!i.matches('.proof-input')||!i.files[0])return;try{state.user||=await ensureIdentity();await uploadProof(i.dataset.task,i.files[0],state.user.id);await loadCollector();notice('Cleanup proof submitted for municipal review.');render()}catch(x){notice(x.message||'Photo upload failed.')}});
app.addEventListener('click',async e=>{if(e.target.closest('[data-action="check-admin"]')){try{await unlockAdmin();notice('Municipal dashboard unlocked.');render()}catch(x){notice(x.message||'Could not unlock dashboard.')}}});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const {action,id,approved,tab}=b.dataset;try{if(tab){state.tab=tab;render();return}if(action==='join')navigate('join');if(action==='back')history.back();if(action==='open-collector'){await loadCollector();navigate('collector')}if(action==='refresh-request'){await loadCollector();notice(`Request is ${state.request?.status||'not found'}.`);render()}if(action==='approve-request'||action==='reject-request'){await reviewCollectorRequest(id,action==='approve-request');await loadAdmin();notice(action==='approve-request'?'Collector approved.':'Collector request rejected.');render()}if(action==='verify-proof'){await verifyProof(id,approved==='true');await loadAdmin();notice(approved==='true'?'Proof verified and points awarded.':'Proof returned to collector.');render()}if(action==='accept-offer'||action==='reject-offer'){await respondToOffer(id,action==='accept-offer');await loadCollector();notice(action==='accept-offer'?'Task accepted.':'Offer rejected: −3 points.');state.tab=action==='accept-offer'?'tasks':'alerts';render()}if(action==='availability'){state.user||=await ensureIdentity();const next=!state.available;if(!navigator.geolocation)throw new Error('Location services are unavailable');navigator.geolocation.getCurrentPosition(async p=>{try{await setAvailability(p.coords.latitude,p.coords.longitude,next);state.available=next;notice(next?'You are available for nearby reports.':'You are unavailable.');render()}catch(x){notice(x.message||'Could not update availability.')}},()=>notice('Allow location access to receive nearby reports.'),{enableHighAccuracy:true,timeout:10000})}}catch(x){notice(x.message||'Could not complete that action.')}});
render();
